Models/Car.cs
namespace Test_Shop_2_1.Models
{
    public class Car
    {
        public int id { set; get; }
        public string name { set; get; }
        public string shortDesc { set; get; }
        public string longDesc { set; get; }
        public string img { set; get; }
        public ushort price { set; get; }
        public bool isFavourite { set; get; }
        public bool available { set; get; }
        public int categoryID { set; get; }
        public virtual Category Category { set; get; }
    }
}

Models/Category.cs
namespace Test_Shop_2_1.Models
{
    public class Category
    {
        public int id { get; set; }
        public string categoryName { get; set; }
        public string desc { get; set; }
        public List<Car> Cars { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Test_Shop_2_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Furniture.cs
namespace Test_Shop_2_1.Models
{
    public class Furniture
    {
        public int id { set; get; }
        public string name { set; get; }
        public string shortDesc { set; get; }
        public string longDesc { set; get; }
        public string img { set; get; }
        public ushort price { set; get; }
        public bool isFavourite { set; get; }
        public bool available { set; get; }
        public int categoryID { set; get; }
        public virtual FurnitureCategory Category { set; get; }
    }
}

Models/FurnitureCategory.cs
namespace Test_Shop_2_1.Models
{
    public class FurnitureCategory
    {
        public int id { get; set; }
        public string categoryName { get; set; }
        public string desc { get; set; }
        public List<Furniture> Furnitures { get; set; }
    }
}

ViewModels/CarsListViewModel.cs
using Test_Shop_2_1.Models;

namespace Test_Shop_2_1.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currCategory { get; set; }

    }
}

Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Test_Shop_2_1.Interfaces;
using Test_Shop_2_1.mocks;
using Test_Shop_2_1.ViewModels;

namespace Test_Shop_2_1.Controllers
{

    public class CarsController : Controller 
    {
        private IAllCars _allCars;
        private ICarsCategory _allCategories;

      

        public ViewResult Index()
        {
            if (_allCars == null)
            {
                _allCars = new MockCars();
            }
            if (_allCategories == null)
            {
                _allCategories = new MockCategory();
            }
            ViewBag.Title = "Страница товаров";
            CarsListViewModel obj = new CarsListViewModel();
            obj.allCars = _allCars.Cars;
            obj.currCategory = "Автомобили";
            return View(obj);
        }

        


    }
}

Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Test_Shop_2_1.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FurnitureController.cs
using Microsoft.AspNetCore.Mvc;
using Test_Shop_2_1.Interfaces;
using Test_Shop_2_1.mocks;

namespace Test_Shop_2_1.Controllers
{
    public class FurnitureController : Controller
    {
        private IAllFurnitures _allFurnitures;
        private IFurnitureCategory _allFurnitureCategories;


        //public FurnitureController(IAllFurnitures iAllFurnitures, IFurnitureCategory iFurnitureCat)
        //{
            //_allFurnitures = iAllFurnitures;
            //_allFurnitureCategories = iFurnitureCat;
        //}
        //Все зелёное не нужно, оно создает ошибку и ломает весь код

        public ViewResult Index()
        {
            if (_allFurnitures == null)
            {
                _allFurnitures = new MockFurnitures();
            }
            if (_allFurnitureCategories == null)
            {
                _allFurnitureCategories = new MockFurnitureCategory();
            }
            var furniture = _allFurnitures.Furnitures;
            return View(furniture);
        }




    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Test_Shop_2_1.Controllers;
using Test_Shop_2_1.Interfaces;
using Test_Shop_2_1.mocks;
using Test_Shop_2_1.Models;

namespace Test_Shop_2_1.Controllers
{
    
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cars/Index.cshtml
<h1>Все товары</h1>
<div class="row mt-5 mb-2">


@{
        <div class="Pologenie">
            <div class="Spisok_Menu Inviz">
                
                <div class="Spisok_Man">
                    <h4>Диваны</h4>
                    <ul>
                        <li><a href="#">Армада</a></li>
                        <li><a href="#">Аврора</a></li>
                        <li><a href="#">Каминное </a></li>
                        <li><a href="#">Бали</a></li>
                        <li><a href="#">Бруклин</a></li>
                        <li><a href="#">Венеция</a></li>
                        <li><a href="#">Лофт</a></li>
                        <li><a href="#">Грация</a></li>
                        <li><a href="#">Валерия</a></li>
                        <li><a href="#">Лотос</a></li>
                        <li><a href="#">Радуга</a></li>
                        <li><a href="#">Соренто</a></li>
                    </ul>
                </div>
                <div class="Spisok_Woman">
                    <h4>Кресла</h4>
                    <ul>
                        <li><a href="">Аврора</a></li>
                        <li><a href="#">Каминное</a></li>
                    </ul>
                </div>
            </div>
        </div>



    //foreach (var car in Model.allCars)
    //{
        //<div class="col-lg-4">
                
            //<img class="img-Product" src="@car.img" alt="@car.name" />
                
            //<h2>@car.name</h2>
            //<p>@car.shortDesc</p>
            //<p>Цена: @car.price.ToString("c")</p>
            //<p><a class="btn btn-warning" href="a">Подробнее</a></p>
        //</div>
    //}
}
</div>

Views/Contacts/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Обратная связь";
}
<h1>Обратная связь</h1>

Views/Furniture/Index.cshtml
@using Test_Shop_2_1.Models
@model IEnumerable<Furniture>


@* <h2>Все товары</h2> *@
<div class="TovarAndSpisok">

    <div class="Pologenie">
        <div class="Spisok_Tovarov">

            <ul>
            <li><a href="#">Вся мебель</a></li>
            </ul>

            <div class="Spisok_Sofa">
                <h4>Диваны</h4>
                <ul>
                    <li><a href="#">Все диваны</a></li>
                    <li><a href="#">Армада1</a></li>
                    <li><a href="#">Аврора2</a></li>
                    <li><a href="#">Каминное3</a></li>
                    <li><a href="#">Бали</a></li>
                    <li><a href="#">Бруклин</a></li>
                    <li><a href="#">Венеция</a></li>
                    <li><a href="#">Лофт</a></li>
                    <li><a href="#">Грация</a></li>
                    <li><a href="#">Валерия</a></li>
                    <li><a href="#">Лотос</a></li>
                    <li><a href="#">Радуга</a></li>
                    <li><a href="#">Соренто</a></li>
                </ul>
            </div>
            <div class="Spisok_Armchair">
                <h4>Кресла</h4>
                <ul>
                    <li><a href="#">Все кресла</a></li>
                    <li><a href="#">Аврора</a></li>
                    <li><a href="#">Каминное</a></li>
                </ul>
            </div>
        </div>
    </div>


    <div class="Tovar">

@{
    foreach(var furniture in Model)
    {
                <div class="TovarAycheyka(@furniture.id)">
            <h2>Модель: @furniture.name</h2>
            <p>Цена: @furniture.price.ToString("c")</p>
                    <button class="Button Button(@furniture.id)">Купить</button>
        </div>
    }

}
    </div>
@* <h1>Все товары</h1> *@

@* <div class="row mt-5 mb-2"> *@



        
</div>
@* </div> *@

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница сайта";
}

<div class="Welcome-to-the-site">
    <h1>Добро пожаловать на наш сайт</h1>
    <h2>Надеюсь вы найдете здесь что-то себе по душе</h2>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин машин</title>
    <title>@ViewBag.Ttitle</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header data-bs-theme="dark">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Carousel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Конфиденциальность</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contacts" asp-action="Index">Обратная связь</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Furniture" asp-action="Index">Список товаров</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container mt-5">
        
            @RenderBody()
       
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2024 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>


    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" ></script>
</body>
</html>